### ISSUE TITLE
mercle hash format

### ISSUE THREAD

**Issue by amiraliziyaei** [amiraliziyaei/kh-blockchain#1]
The file below is an improved version of Merkel's initial version.
![image](https://user-images.githubusercontent.com/115802664/221248314-b1f79e6a-2d73-4a92-a315-dd7e6c67ee27.png)

To test the correctness of the logic of the program, I ran the following test:
`tnxs = [{"hash": "1"}, {"hash": "2"}]`
`m = mercle(tnxs)`
`print(m.get_root())`
The output was:
`['6b51d431df5d7f141cbececcf79edf3dd861c3b4069f0b11661a3eefacbba918']`
But when I manually tested these two hashes in idle, I got a different output:
![image](https://user-images.githubusercontent.com/115802664/221247622-0a072308-abef-424f-b8d8-18601ae194fd.png)
I think the root of this problem can be in the format of using hashes.
Tnx!

**Comment by AliasgharFahmidekar** [comment]
I think for first hashing we should have a if
Because now we before hashing add first str with second str
So write a if for first hashing before for loop and if first hash we should first hash x and then go to for loop
So for loop in else
